name: CI

on:
  merge_group:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*

      # 👇 AGREGA ESTO
      - run: npm install -g pnpm

      # 👇 CAMBIA ESTO
      - run: pnpm install

      - run: pnpm run type-check
      - run: pnpm run lint --max-warnings=0 -f gha